### ISSUE TITLE
Default config file & no-config-file error

### ISSUE THREAD

**Issue by gillchristian** [Huemul/chimi#19]
CLI defaults to `.chimirc` as the config file and if it is not present the process shows an error.

We could either remove the default config file from the CLI or not error when `.chimirc` is not found.

**Comment by fvictorio** [comment]
This is already fixed, right?

We have another issue, I think. I created a `chimi.config.js` file and ran `chimi` and it used the default config.

**Comment by gillchristian** [comment]
I think is not entirely fixed. Will look into this this week.

**Comment by gillchristian** [comment]
Let's use this package [cosmiconfig](https://github.com/davidtheclark/cosmiconfig).

**Comment by gillchristian** [comment]
#29
